/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class NumVector extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NumVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NumVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_NumVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NumVector(long[] initialElements) {
    this();
    reserve(initialElements.length);

    for (long element : initialElements) {
      add(element);
    }
  }

  public NumVector(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public NumVector() {
    this(manateeJNI.new_NumVector__SWIG_0(), true);
  }

  public NumVector(NumVector other) {
    this(manateeJNI.new_NumVector__SWIG_1(NumVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return manateeJNI.NumVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    manateeJNI.NumVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return manateeJNI.NumVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    manateeJNI.NumVector_clear(swigCPtr, this);
  }

  public NumVector(int count, long value) {
    this(manateeJNI.new_NumVector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return manateeJNI.NumVector_doSize(swigCPtr, this);
  }

  private void doAdd(long x) {
    manateeJNI.NumVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, long x) {
    manateeJNI.NumVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private long doRemove(int index) {
    return manateeJNI.NumVector_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return manateeJNI.NumVector_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long val) {
    return manateeJNI.NumVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    manateeJNI.NumVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
